# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_MainApp.ui'
#
# Created: Wed May 18 13:55:50 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(918, 332)
        MainApp.setLayoutDirection(Qt.LeftToRight)
        self.centralWidget = QWidget(MainApp)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QGridLayout(self.centralWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QSplitter(self.centralWidget)
        self.splitter.setOrientation(Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.stackedWidget = QStackedWidget(self.splitter)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.importPage = QWidget()
        self.importPage.setObjectName("importPage")
        self.gridLayout_10 = QGridLayout(self.importPage)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea_5 = QScrollArea(self.importPage)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 409, 294))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_11 = QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget = QWidget(self.scrollAreaWidgetContents_5)
        self.widget.setObjectName("widget")
        self.gridLayout_17 = QGridLayout(self.widget)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox = QGroupBox(self.widget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setContentsMargins(9, 7, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rb_file = QRadioButton(self.groupBox)
        self.rb_file.setChecked(True)
        self.rb_file.setObjectName("rb_file")
        self.horizontalLayout_6.addWidget(self.rb_file)
        self.rb_directory = QRadioButton(self.groupBox)
        self.rb_directory.setObjectName("rb_directory")
        self.horizontalLayout_6.addWidget(self.rb_directory)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_17.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem1 = QSpacerItem(20, 13, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_12 = QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pb_nextFile = QPushButton(self.widget)
        self.pb_nextFile.setMinimumSize(QSize(0, 0))
        self.pb_nextFile.setMaximumSize(QSize(27, 27))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.pb_nextFile.setFont(font)
        self.pb_nextFile.setStyleSheet("")
        self.pb_nextFile.setAutoRepeat(False)
        self.pb_nextFile.setAutoDefault(False)
        self.pb_nextFile.setDefault(False)
        self.pb_nextFile.setFlat(False)
        self.pb_nextFile.setObjectName("pb_nextFile")
        self.gridLayout_12.addWidget(self.pb_nextFile, 0, 2, 1, 1)
        self.label_2 = QLabel(self.widget)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vfkFileLineEdit = QLineEdit(self.widget)
        self.vfkFileLineEdit.setObjectName("vfkFileLineEdit")
        self.horizontalLayout_3.addWidget(self.vfkFileLineEdit)
        self.browseButton = QPushButton(self.widget)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_3.addWidget(self.browseButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.budCheckBox = QCheckBox(self.widget)
        self.budCheckBox.setChecked(True)
        self.budCheckBox.setObjectName("budCheckBox")
        self.gridLayout_12.addWidget(self.budCheckBox, 2, 1, 1, 1)
        self.label = QLabel(self.widget)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 0, 0, 1, 1)
        self.parCheckBox = QCheckBox(self.widget)
        self.parCheckBox.setChecked(True)
        self.parCheckBox.setObjectName("parCheckBox")
        self.gridLayout_12.addWidget(self.parCheckBox, 1, 1, 1, 1)
        self.l_settings = QLabel(self.widget)
        self.l_settings.setMinimumSize(QSize(69, 0))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_settings.setFont(font)
        self.l_settings.setObjectName("l_settings")
        self.gridLayout_12.addWidget(self.l_settings, 3, 0, 1, 1)
        self.overwriteCheckBox = QCheckBox(self.widget)
        self.overwriteCheckBox.setChecked(False)
        self.overwriteCheckBox.setObjectName("overwriteCheckBox")
        self.gridLayout_12.addWidget(self.overwriteCheckBox, 3, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.labelLoading = QLabel(self.widget)
        self.labelLoading.setText("")
        self.labelLoading.setObjectName("labelLoading")
        self.gridLayout_17.addWidget(self.labelLoading, 3, 0, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QProgressBar(self.widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.loadVfkButton = QPushButton(self.widget)
        self.loadVfkButton.setObjectName("loadVfkButton")
        self.horizontalLayout_2.addWidget(self.loadVfkButton)
        self.gridLayout_17.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.gridLayout_11.addWidget(self.widget, 1, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_10.addWidget(self.scrollArea_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.importPage)
        self.changesPage = QWidget()
        self.changesPage.setObjectName("changesPage")
        self.gridLayout_15 = QGridLayout(self.changesPage)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.scrollArea_6 = QScrollArea(self.changesPage)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QRect(0, 0, 269, 194))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_16 = QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widget_3 = QWidget(self.scrollAreaWidgetContents_6)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_14 = QGridLayout(self.widget_3)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_4 = QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_mainDb = QLineEdit(self.widget_3)
        self.le_mainDb.setObjectName("le_mainDb")
        self.gridLayout_13.addWidget(self.le_mainDb, 0, 1, 1, 1)
        self.pb_mainDb = QPushButton(self.widget_3)
        self.pb_mainDb.setObjectName("pb_mainDb")
        self.gridLayout_13.addWidget(self.pb_mainDb, 0, 2, 1, 1)
        self.label_5 = QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_13.addWidget(self.label_5, 1, 0, 1, 1)
        self.le_amendmentDb = QLineEdit(self.widget_3)
        self.le_amendmentDb.setObjectName("le_amendmentDb")
        self.gridLayout_13.addWidget(self.le_amendmentDb, 1, 1, 1, 1)
        self.pb_amendmentDb = QPushButton(self.widget_3)
        self.pb_amendmentDb.setObjectName("pb_amendmentDb")
        self.gridLayout_13.addWidget(self.pb_amendmentDb, 1, 2, 1, 1)
        self.label_6 = QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_13.addWidget(self.label_6, 2, 0, 1, 1)
        self.le_exportDb = QLineEdit(self.widget_3)
        self.le_exportDb.setObjectName("le_exportDb")
        self.gridLayout_13.addWidget(self.le_exportDb, 2, 1, 1, 1)
        self.pb_exportDb = QPushButton(self.widget_3)
        self.pb_exportDb.setObjectName("pb_exportDb")
        self.gridLayout_13.addWidget(self.pb_exportDb, 2, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        spacerItem2 = QSpacerItem(20, 38, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem2, 1, 0, 1, 1)
        self.l_status = QLabel(self.widget_3)
        self.l_status.setText("")
        self.l_status.setObjectName("l_status")
        self.gridLayout_14.addWidget(self.l_status, 2, 0, 1, 1)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progressBar_Changes = QProgressBar(self.widget_3)
        self.progressBar_Changes.setProperty("value", 0)
        self.progressBar_Changes.setObjectName("progressBar_Changes")
        self.horizontalLayout_5.addWidget(self.progressBar_Changes)
        self.pb_applyChanges = QPushButton(self.widget_3)
        self.pb_applyChanges.setObjectName("pb_applyChanges")
        self.horizontalLayout_5.addWidget(self.pb_applyChanges)
        self.gridLayout_14.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.gridLayout_16.addWidget(self.widget_3, 0, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_15.addWidget(self.scrollArea_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.changesPage)
        self.searchPage = QWidget()
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchPage.sizePolicy().hasHeightForWidth())
        self.searchPage.setSizePolicy(sizePolicy)
        self.searchPage.setObjectName("searchPage")
        self.verticalLayout_3 = QVBoxLayout(self.searchPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QLabel(self.searchPage)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.searchCombo = QComboBox(self.searchPage)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchCombo.sizePolicy().hasHeightForWidth())
        self.searchCombo.setSizePolicy(sizePolicy)
        self.searchCombo.setObjectName("searchCombo")
        self.horizontalLayout_4.addWidget(self.searchCombo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.searchForms = QStackedWidget(self.searchPage)
        self.searchForms.setObjectName("searchForms")
        self.page = QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 48, 28))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vlastniciSearchForm = VlastniciSearchForm(self.scrollAreaWidgetContents)
        self.vlastniciSearchForm.setObjectName("vlastniciSearchForm")
        self.gridLayout_5.addWidget(self.vlastniciSearchForm, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.searchForms.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_3 = QScrollArea(self.page_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 66, 28))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_7 = QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.parcelySearchForm = ParcelySearchForm(self.scrollAreaWidgetContents_2)
        self.parcelySearchForm.setObjectName("parcelySearchForm")
        self.gridLayout_7.addWidget(self.parcelySearchForm, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.searchForms.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_2 = QGridLayout(self.page_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_2 = QScrollArea(self.page_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 66, 28))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.budovySearchForm = BudovySearchForm(self.scrollAreaWidgetContents_3)
        self.budovySearchForm.setObjectName("budovySearchForm")
        self.gridLayout_3.addWidget(self.budovySearchForm, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.searchForms.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_8 = QGridLayout(self.page_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea_4 = QScrollArea(self.page_4)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 66, 28))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_9 = QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.jednotkySearchForm = JednotkySearchForm(self.scrollAreaWidgetContents_4)
        self.jednotkySearchForm.setObjectName("jednotkySearchForm")
        self.gridLayout_9.addWidget(self.jednotkySearchForm, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_8.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.searchForms.addWidget(self.page_4)
        self.verticalLayout_3.addWidget(self.searchForms)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.searchButton = QPushButton(self.searchPage)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.searchPage)
        self.widget_2 = QWidget(self.splitter)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.rightWidgetLayout = QVBoxLayout(self.widget_2)
        self.rightWidgetLayout.setMargin(0)
        self.rightWidgetLayout.setObjectName("rightWidgetLayout")
        self.vfkBrowser = VfkTextBrowser(self.widget_2)
        self.vfkBrowser.setObjectName("vfkBrowser")
        self.rightWidgetLayout.addWidget(self.vfkBrowser)
        self.gridLayout_4.addWidget(self.splitter, 0, 1, 1, 1)
        MainApp.setWidget(self.centralWidget)
        self.actionVyhledavani = QAction(MainApp)
        self.actionVyhledavani.setCheckable(True)
        icon = QIcon()
        icon.addPixmap(QPixmap(":/search.png"), QIcon.Normal, QIcon.Off)
        self.actionVyhledavani.setIcon(icon)
        self.actionVyhledavani.setObjectName("actionVyhledavani")
        self.actionImport = QAction(MainApp)
        self.actionImport.setCheckable(True)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/db-add.png"), QIcon.Normal, QIcon.Off)
        self.actionImport.setIcon(icon1)
        self.actionImport.setObjectName("actionImport")
        self.actionBack = QAction(MainApp)
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/arrowBack.png"), QIcon.Normal, QIcon.Off)
        self.actionBack.setIcon(icon2)
        self.actionBack.setObjectName("actionBack")
        self.actionForward = QAction(MainApp)
        self.actionForward.setEnabled(True)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(":/arrowForward.png"), QIcon.Normal, QIcon.Off)
        self.actionForward.setIcon(icon3)
        self.actionForward.setObjectName("actionForward")
        self.actionExportLatex = QAction(MainApp)
        self.actionExportLatex.setObjectName("actionExportLatex")
        self.actionExportHtml = QAction(MainApp)
        self.actionExportHtml.setObjectName("actionExportHtml")
        self.actionSelectParInMap = QAction(MainApp)
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(":/selectPar.png"), QIcon.Normal, QIcon.Off)
        self.actionSelectParInMap.setIcon(icon4)
        self.actionSelectParInMap.setObjectName("actionSelectParInMap")
        self.actionSelectBudInMap = QAction(MainApp)
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(":/selectBud.png"), QIcon.Normal, QIcon.Off)
        self.actionSelectBudInMap.setIcon(icon5)
        self.actionSelectBudInMap.setObjectName("actionSelectBudInMap")
        self.actionCuzkPage = QAction(MainApp)
        icon6 = QIcon()
        icon6.addPixmap(QPixmap(":/cuzk.png"), QIcon.Normal, QIcon.Off)
        self.actionCuzkPage.setIcon(icon6)
        self.actionCuzkPage.setObjectName("actionCuzkPage")
        self.actionShowInfoaboutSelection = QAction(MainApp)
        self.actionShowInfoaboutSelection.setCheckable(True)
        icon7 = QIcon()
        icon7.addPixmap(QPixmap(":/showInfo.png"), QIcon.Normal, QIcon.Off)
        self.actionShowInfoaboutSelection.setIcon(icon7)
        self.actionShowInfoaboutSelection.setObjectName("actionShowInfoaboutSelection")
        self.actionShowHelpPage = QAction(MainApp)
        icon8 = QIcon()
        icon8.addPixmap(QPixmap(":/vfkPlugin.png"), QIcon.Normal, QIcon.Off)
        self.actionShowHelpPage.setIcon(icon8)
        self.actionShowHelpPage.setObjectName("actionShowHelpPage")
        self.actionZpracujZmeny = QAction(MainApp)
        self.actionZpracujZmeny.setCheckable(True)
        icon9 = QIcon()
        icon9.addPixmap(QPixmap(":/applyChanges.png"), QIcon.Normal, QIcon.Off)
        self.actionZpracujZmeny.setIcon(icon9)
        self.actionZpracujZmeny.setObjectName("actionZpracujZmeny")

        self.retranslateUi(MainApp)
        self.stackedWidget.setCurrentIndex(0)
        self.searchForms.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainApp)

    def retranslateUi(self, MainApp):
        MainApp.setWindowTitle(_translate("MainApp", "Prohlížeč VFK", None))
        self.groupBox.setTitle(_translate("MainApp", "Vstupní zdroj:", None))
        self.rb_file.setToolTip(_translate("MainApp", "Načti soubor", None))
        self.rb_file.setText(_translate("MainApp", "Soubor", None))
        self.rb_directory.setToolTip(_translate("MainApp", "Načti VFK soubory z adresáře", None))
        self.rb_directory.setText(_translate("MainApp", "Adresář", None))
        self.pb_nextFile.setText(_translate("MainApp", "+", None))
        self.label_2.setText(_translate("MainApp", "Vrstvy:", None))
        self.browseButton.setText(_translate("MainApp", "Procházet", None))
        self.budCheckBox.setText(_translate("MainApp", "Budovy (BUD)", None))
        self.label.setText(_translate("MainApp", "VFK soubor:", None))
        self.parCheckBox.setText(_translate("MainApp", "Parcely (PAR)", None))
        self.l_settings.setText(_translate("MainApp", "Možnosti:", None))
        self.overwriteCheckBox.setToolTip(_translate("MainApp", "Přepiš stávající databázi SQLite", None))
        self.overwriteCheckBox.setText(_translate("MainApp", "Přepsat stávající databázi", None))
        self.loadVfkButton.setText(_translate("MainApp", "Načíst", None))
        self.label_4.setText(_translate("MainApp", "Hlavní databáze:", None))
        self.pb_mainDb.setText(_translate("MainApp", "Procházet", None))
        self.label_5.setText(_translate("MainApp", "Změnová databáze:", None))
        self.pb_amendmentDb.setText(_translate("MainApp", "Procházet", None))
        self.label_6.setText(_translate("MainApp", "Výstupní databáze:", None))
        self.pb_exportDb.setText(_translate("MainApp", "Procházet", None))
        self.pb_applyChanges.setText(_translate("MainApp", "Zpracovat změny", None))
        self.label_3.setText(_translate("MainApp", "Vyhledat:", None))
        self.searchButton.setText(_translate("MainApp", "Hledej", None))
        self.actionVyhledavani.setText(_translate("MainApp", "Vyhledávání", None))
        self.actionVyhledavani.setToolTip(_translate("MainApp", "Vyhledávání", None))
        self.actionVyhledavani.setShortcut(_translate("MainApp", "Ctrl+F", None))
        self.actionImport.setText(_translate("MainApp", "Import", None))
        self.actionImport.setToolTip(_translate("MainApp", "Import VFK", None))
        self.actionImport.setShortcut(_translate("MainApp", "Ctrl+I", None))
        self.actionBack.setText(_translate("MainApp", "back", None))
        self.actionBack.setToolTip(_translate("MainApp", "Zpět", None))
        self.actionBack.setShortcut(_translate("MainApp", "Ctrl+Z", None))
        self.actionForward.setText(_translate("MainApp", "forward", None))
        self.actionForward.setToolTip(_translate("MainApp", "Vpřed", None))
        self.actionForward.setShortcut(_translate("MainApp", "Ctrl+Shift+Z", None))
        self.actionExportLatex.setText(_translate("MainApp", "LaTeX", None))
        self.actionExportLatex.setToolTip(_translate("MainApp", "Export do LaTeXu", None))
        self.actionExportHtml.setText(_translate("MainApp", "HTML", None))
        self.actionExportHtml.setToolTip(_translate("MainApp", "Export do HTML", None))
        self.actionSelectParInMap.setText(_translate("MainApp", "selectParInMap", None))
        self.actionSelectParInMap.setToolTip(_translate("MainApp", "Označit aktuální parcely v mapě", None))
        self.actionSelectParInMap.setShortcut(_translate("MainApp", "Ctrl+P", None))
        self.actionSelectBudInMap.setText(_translate("MainApp", "selectBudInMap", None))
        self.actionSelectBudInMap.setToolTip(_translate("MainApp", "Označit aktuální budovy v mapě", None))
        self.actionSelectBudInMap.setShortcut(_translate("MainApp", "Ctrl+B", None))
        self.actionCuzkPage.setText(_translate("MainApp", "cuzkPage", None))
        self.actionCuzkPage.setToolTip(_translate("MainApp", "Otevřít v prohlížeči aplikaci Nahlížení do KN pro aktuální nemovitost", None))
        self.actionShowInfoaboutSelection.setText(_translate("MainApp", "showInfoaboutSelection", None))
        self.actionShowInfoaboutSelection.setToolTip(_translate("MainApp", "Aktivovat/deaktivovat zobrazení informací o vybraných nemovitostech", None))
        self.actionShowHelpPage.setText(_translate("MainApp", "showHelpPage", None))
        self.actionShowHelpPage.setToolTip(_translate("MainApp", "Zobrazit nápovědu", None))
        self.actionShowHelpPage.setShortcut(_translate("MainApp", "Ctrl+H", None))
        self.actionZpracujZmeny.setText(_translate("MainApp", "ZpracujZmeny", None))
        self.actionZpracujZmeny.setToolTip(_translate("MainApp", "Aplikuj změny na stavová data", None))
        self.actionZpracujZmeny.setShortcut(_translate("MainApp", "Ctrl+A", None))

from .vlastniciSearchForm import VlastniciSearchForm
from .vfkTextBrowser import VfkTextBrowser
from .jednotkySearchForm import JednotkySearchForm
from .budovySearchForm import BudovySearchForm
from .parcelySearchForm import ParcelySearchForm
from .resources import *    
